FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/python:3.11-slim AS builder

WORKDIR /build

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt --target /build/packages

FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/python:3.11-slim

WORKDIR /app

COPY --from=builder /build/packages /app/packages

COPY . .

ENV PYTHONPATH=/app/packages

EXPOSE 5000

CMD ["python", "app.py"]